-- Budget redesign: cache table for Sam's Take Today panel.
--
-- Sam's Take is a 3-4 sentence coaching paragraph generated by Haiku that
-- references the candidate's actual budget numbers. It's expensive to
-- generate (one Haiku call per refresh) and the underlying budget data
-- doesn't change minute-to-minute, so we cache the response with a 24h TTL.
--
-- One row per workspace (PK on workspace_owner_id). Each refresh
-- overwrites the row. budget_snapshot stores the JSON inputs that were
-- used to generate the content — kept as an audit trail so we can verify
-- "was this take generated against the same numbers we're showing?" if a
-- discrepancy ever shows up.
--
-- Cache TTL is enforced in the read query, not via a separate expiry
-- column: SELECT ... WHERE generated_at > datetime('now', '-24 hours').
--
-- Rollback: DROP TABLE budget_sams_take.

CREATE TABLE IF NOT EXISTS budget_sams_take (
  workspace_owner_id TEXT PRIMARY KEY,
  campaign_id        TEXT,
  content            TEXT NOT NULL,
  generated_at       TEXT NOT NULL,
  budget_snapshot    TEXT
);
