-- Generated by import_campaign_reference.mjs
-- Source: scripts/import_data/texas_sample.json
-- Batch ID: batch_2026-05-09T18-42-42_texas_sample
-- Rows: 5
-- Generated: 2026-05-09T18:42:42.993Z

INSERT INTO campaign_reference (id, state, office_level, category, question, question_variants, answer, source_url, source_name, last_verified_date, update_frequency, verification_method, scope, import_batch_id) VALUES
  ('cc7c5ebdbaa03915', 'TX', '["state","district","county","local"]', 'finance_ethics', 'Do I need a campaign treasurer even if I don''t raise money?', '["When do I have to appoint a campaign treasurer?","Do I need a treasurer before fundraising?","Can I spend my own money before filing a treasurer appointment?"]', 'Yes. You must file a Campaign Treasurer Appointment (Form CTA) with the appropriate authority before you can accept any contributions, make any expenditures, or even publicly announce your candidacy for office.', 'https://www.ethics.state.tx.us/resources/FAQs/FAQ_COH_Legal.php', 'Texas Ethics Commission – Campaign Treasurer FAQ', '2026-05-09', 'static', 'official_source_direct', 'Applies to all candidates seeking state, district, county, or local office in Texas.', 'batch_2026-05-09T18-42-42_texas_sample'),
  ('d2da327fa252c941', 'TX', '["federal","state","district","county","local"]', 'election_dates', 'When is the 2026 Primary Runoff and when does early voting start?', '["What is the date of the primary runoff?","When can I start voting in the runoff?","Runoff election dates 2026"]', 'The 2026 Primary Runoff Election Day is Tuesday, May 26, 2026. Early voting for the runoff begins on Monday, May 18, 2026, and ends on Friday, May 22, 2026.', 'https://www.sos.state.tx.us/elections/voter/important-election-dates.shtml', 'Texas Secretary of State – Important Election Dates', '2026-05-09', 'per_cycle', 'official_source_direct', 'Applies to all Texas voters and candidates with primary runoffs on the ballot.', 'batch_2026-05-09T18-42-42_texas_sample'),
  ('078773413cc3e26a', 'TX', '["state","district","county","local"]', 'ballot_access', 'If I lost my primary, can I run as an independent in the general election?', '["Does Texas have a sore loser law?","Can a primary loser run in November?","Can I be a write-in after losing a primary?"]', 'No. Under Texas Election Code § 162.015, a person who was a candidate in a primary election is ineligible to be an independent candidate or a write-in candidate for that same office in the succeeding general election.', 'https://statutes.capitol.texas.gov/Docs/EL/htm/EL.162.htm#162.015', 'Texas Election Code § 162.015', '2026-05-09', 'static', 'statute_citation', 'Applies to all candidates who participated in a primary election cycle.', 'batch_2026-05-09T18-42-42_texas_sample'),
  ('7347b02cee11bd44', 'TX', '["state","district"]', 'residency', 'How long do I have to live in my district before I can run for State Representative?', '["What are the residency requirements for State House?","How long must I be a resident of my district?","Residency rules for TX House candidates"]', 'A candidate for State Representative must have lived in Texas for two years and in the specific district for one year immediately preceding the date of the election.', 'https://www.sos.state.tx.us/elections/candidates/guide/2026/qualifications2026.shtml', 'Texas Secretary of State – Candidate Qualifications 2026', '2026-05-09', 'static', 'official_source_direct', 'Applies to all candidates for the Texas House of Representatives.', 'batch_2026-05-09T18-42-42_texas_sample'),
  ('9147a43c5789d57b', 'TX', '["state","district","county","local"]', 'candidate_eligibility', 'Can I run for office if I have a past felony conviction?', '["Felony rules for TX candidates","Can a felon run for office in Texas?","Restoration of rights for running for office"]', 'A person convicted of a felony is ineligible to run for office unless they have been pardoned or otherwise released from the resulting disabilities of the conviction (e.g., completed all terms of their sentence, including parole).', 'https://statutes.capitol.texas.gov/Docs/EL/htm/EL.141.htm#141.001', 'Texas Election Code § 141.001', '2026-05-09', 'static', 'statute_citation', 'Applies to all candidates for public office in Texas.', 'batch_2026-05-09T18-42-42_texas_sample')
ON CONFLICT(id) DO UPDATE SET
  office_level = excluded.office_level,
  category = excluded.category,
  question = excluded.question,
  question_variants = excluded.question_variants,
  answer = excluded.answer,
  source_url = excluded.source_url,
  source_name = excluded.source_name,
  last_verified_date = excluded.last_verified_date,
  update_frequency = excluded.update_frequency,
  verification_method = excluded.verification_method,
  scope = excluded.scope,
  import_batch_id = excluded.import_batch_id,
  updated_at = datetime('now');
